# Generated by Django 5.2.8 on 2025-12-18 05:25

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_session',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study_session',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study_session',
            name='goal_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study_session',
            name='goal_time',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study_session',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study_session',
            name='study_subject',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study_session',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
