# Generated by Django 5.2.8 on 2026-01-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_session', '0002_add_user_field'),
        ('study_session', '0002_study_session_date_study_session_end_time_and_more'),
    ]

    operations = [
    ]
