# Generated by Django 5.2.8 on 2026-01-07 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_session', '0003_make_user_required'),
        ('study_session', '0003_merge_20260107_1350'),
    ]

    operations = [
    ]
