# Generated by Django 5.2.8 on 2026-01-10 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
        ('study_session', '0004_merge_20260107_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_session',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_sessions', to='challenge.challenge'),
        ),
    ]
